# Generated by Django 3.2.8 on 2021-10-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.BigIntegerField(null=True)),
                ('location_name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('no_of_known_locations', models.BigIntegerField(null=True)),
                ('no_of_unknown_locations', models.BigIntegerField(null=True)),
                ('temp_exists_on_api', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnknownLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.BigIntegerField(null=True)),
                ('location_name', models.TextField(blank=True)),
                ('weather_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature.weather')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(blank=True)),
                ('value', models.FloatField(null=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='weather_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature.weather'),
        ),
    ]
